### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by anshulvj** [code-iai/iai_kinect2#112]
(**EDIT 2**: OK. So I just read [issue](https://github.com/code-iai/iai_kinect2/issues/102) that relates to my EDIT 1, and apparently switching to OpenCV 2.4.9 solves the issue?? That post shows a lot of errors and changes after that dude switched opencv version so wondering whether there are any other instructions before I should compile OpenCV 2.4.9?). I'm following instructions given at https://github.com/code-iai/iai_kinect2 so I'm assuming they're updated.

(**EDIT 1**: Got different error after making changes. explanation after details of error # (2))

I am installing iai_kinect2 on ubuntu 14.04. I have successfully installed OpenCL, ROS Hydro, OpenCV, PCL, Eigen3, libfreenect2 in that order. When I run the iai_kinect2 setup the error (detailed below) occurs and I'm not sure what to do; didn't glean too much googling the errors, and I re-checked the installation (everything except libturbojpeg0-dev, as I could not find it, but that command is commented out in the libfreenect2 setup). If something is obviously wrong please let me know. I just spent 4 days installing Opencv (had to install w/o ffmpeg), opencl, Ros and pcl so I hope nothing is wrong with that :(. 

I installed pcl 1.7 following directions [here](http://pointclouds.org/downloads/source.html), Opencv 3.0.0 from [here](http://rodrigoberriel.com/2014/10/installing-opencv-3-0-0-on-ubuntu-14-04/), Opencl from Beignet official [website](http://www.freedesktop.org/wiki/Software/Beignet/) and [here](http://arrayfire.com/opencl-on-intel-hd-iris-graphics-on-linux/). "clinfo" for opencl shows it's installed (libfreenect2 protonect cl ran succesfully so that's not an issue), opencv examples ran fine and pcl installation did not show any errors. But the errors below seem to be initiated from pcl installation (it takes 4 hrs to make on my embedded machine so I'm reluctant to re-make it unless I'm absolutely sure errors are coming from there).

Thanks in advance

The entire error I am getting is:

**1) Error running rosdep:**

anshulvj@anshulspc:~/catkin_ws/src/iai_kinect2$ rosdep install -r --from-paths .
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
kinect2_viewer: Cannot locate rosdep definition for [kinect2_bridge]
kinect2_bridge: Cannot locate rosdep definition for [kinect2_registration]
kinect2_calibration: Cannot locate rosdep definition for [kinect2_bridge]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

**2) Error running catkin_make:**

[100%] Building CXX object iai_kinect2/kinect2_bridge/CMakeFiles/kinect2_bridge.dir/src/kinect2_bridge.cpp.o
In file included from /usr/include/pcl-1.7/pcl/visualization/cloud_viewer.h:39:0,
                 from /home/anshulvj/catkin_ws/src/iai_kinect2/kinect2_viewer/src/viewer.cpp:32:
/usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:283:88: error: macro "PCL_DEPRECATED" requires 2 arguments, but only 1 given
         "addCoordinateSystem (scale, id, viewport) with id a unique string identifier.")
                                                                                        ^
/usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:304:97: error: macro "PCL_DEPRECATED" requires 2 arguments, but only 1 given
         "addCoordinateSystem (scale, x, y, z, id, viewport) with id a unique string identifier.")
                                                                                                 ^
/usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:327:91: error: macro "PCL_DEPRECATED" requires 2 arguments, but only 1 given
         "addCoordinateSystem (scale, t, id, viewport) with id a unique string identifier.")
                                                                                           ^
/usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:374:81: error: macro "PCL_DEPRECATED" requires 2 arguments, but only 1 given
         "addCoordinateSystem (id, viewport) with id a unique string identifier.")
                                                                                 ^
/home/anshulvj/catkin_ws/src/iai_kinect2/kinect2_calibration/src/kinect2_calibration.cpp: In member function ‘void CameraCalibration::calibrateExtrinsics()’:
/home/anshulvj/catkin_ws/src/iai_kinect2/kinect2_calibration/src/kinect2_calibration.cpp:682:56: error: cannot convert ‘const cv::TermCriteria’ to ‘int’ for argument ‘13’ to ‘double cv::stereoCalibrate(cv::InputArrayOfArrays, cv::InputArrayOfArrays, cv::InputArrayOfArrays, cv::InputOutputArray, cv::InputOutputArray, cv::InputOutputArray, cv::InputOutputArray, cv::Size, cv::OutputArray, cv::OutputArray, cv::OutputArray, cv::OutputArray, int, cv::TermCriteria)’
                                 cv::CALIB_FIX_INTRINSIC);
                                                        ^
/home/anshulvj/catkin_ws/src/iai_kinect2/kinect2_calibration/src/kinect2_calibration.cpp: In member function ‘void DepthCalibration::getPlane(size_t, cv::Mat&, double&) const’:
/home/anshulvj/catkin_ws/src/iai_kinect2/kinect2_calibration/src/kinect2_calibration.cpp:969:138: error: ‘ITERATIVE’ is not a member of ‘cv’
     cv::solvePnPRansac(board, points[index], cameraMatrix, distortion, rvec, translation, false, 300, 0.05, board.size(), cv::noArray(), cv::ITERATIVE);
                                                                                                                                          ^
make[2]: *** [iai_kinect2/kinect2_calibration/CMakeFiles/kinect2_calibration.dir/src/kinect2_calibration.cpp.o] Error 1
make[1]: *** [iai_kinect2/kinect2_calibration/CMakeFiles/kinect2_calibration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:281:9: error: ‘PCL_DEPRECATED’ does not name a type
         PCL_DEPRECATED (
         ^
/usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:302:9: error: ‘PCL_DEPRECATED’ does not name a type
         PCL_DEPRECATED (
         ^
/usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:325:9: error: ‘PCL_DEPRECATED’ does not name a type
         PCL_DEPRECATED (
         ^
/usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:372:9: error: ‘PCL_DEPRECATED’ does not name a type
         PCL_DEPRECATED (
         ^
Linking CXX executable /home/anshulvj/catkin_ws/devel/lib/kinect2_bridge/kinect2_bridge
Linking CXX shared library /home/anshulvj/catkin_ws/devel/lib/libkinect2_bridge_nodelet.so
/usr/bin/ld: warning: libopencv_imgproc.so.3.0, needed by /home/anshulvj/catkin_ws/devel/lib/libkinect2_registration.so, may conflict with libopencv_imgproc.so.2.4
/usr/local/lib/libfreenect2.a(turbo_jpeg_rgb_packet_processor.cpp.o): In function `libfreenect2::TurboJpegRgbPacketProcessor::process(libfreenect2::RgbPacket const&)':
/home/anshulvj/libfreenect2/examples/protonect/src/turbo_jpeg_rgb_packet_processor.cpp:118: undefined reference to `tjDecompress2'
/home/anshulvj/libfreenect2/examples/protonect/src/turbo_jpeg_rgb_packet_processor.cpp:129: undefined reference to `tjGetErrorStr'
/usr/local/lib/libfreenect2.a(turbo_jpeg_rgb_packet_processor.cpp.o): In function `~TurboJpegRgbPacketProcessorImpl':
/home/anshulvj/libfreenect2/examples/protonect/src/turbo_jpeg_rgb_packet_processor.cpp:67: undefined reference to `tjDestroy'
/home/anshulvj/libfreenect2/examples/protonect/src/turbo_jpeg_rgb_packet_processor.cpp:69: undefined reference to `tjGetErrorStr'
/usr/local/lib/libfreenect2.a(turbo_jpeg_rgb_packet_processor.cpp.o): In function `libfreenect2::TurboJpegRgbPacketProcessor::TurboJpegRgbPacketProcessor()':
/home/anshulvj/libfreenect2/examples/protonect/src/turbo_jpeg_rgb_packet_processor.cpp:50: undefined reference to `tjInitDecompress'
/home/anshulvj/libfreenect2/examples/protonect/src/turbo_jpeg_rgb_packet_processor.cpp:53: undefined reference to `tjGetErrorStr'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `libfreenect2::Freenect2DeviceImpl::close()':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:616: undefined reference to `libusb_close'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `libfreenect2::operator<<(std::ostream&, libfreenect2::PrintBusAndDevice const&)':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:109: undefined reference to `libusb_get_device_address'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:109: undefined reference to `libusb_get_bus_number'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `libfreenect2::Freenect2DeviceImpl::isSameUsbDevice(libusb_device*)':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:352: undefined reference to `libusb_get_bus_number'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:353: undefined reference to `libusb_get_device_address'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:355: undefined reference to `libusb_get_bus_number'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:356: undefined reference to `libusb_get_device_address'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `libfreenect2::Freenect2Impl::clearDeviceEnumeration()':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:217: undefined reference to `libusb_unref_device'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `libfreenect2::Freenect2::openDevice(int, libfreenect2::PacketPipeline const*, bool)':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:694: undefined reference to `libusb_open'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:704: undefined reference to `libusb_reset_device'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:716: undefined reference to `libusb_close'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `libfreenect2::Freenect2Impl::clearDeviceEnumeration()':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:217: undefined reference to `libusb_unref_device'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `Freenect2Impl':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:139: undefined reference to `libusb_init'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `libfreenect2::Freenect2Impl::clearDeviceEnumeration()':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:217: undefined reference to `libusb_unref_device'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `~Freenect2Impl':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:159: undefined reference to `libusb_exit'
/usr/local/lib/libfreenect2.a(libfreenect2.cpp.o): In function `libfreenect2::Freenect2Impl::enumerateDevices()':
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:228: undefined reference to `libusb_get_device_list'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:289: undefined reference to `libusb_unref_device'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:239: undefined reference to `libusb_get_device_descriptor'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:258: undefined reference to `libusb_open'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:263: undefined reference to `libusb_get_string_descriptor_ascii'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:281: undefined reference to `libusb_close'
/home/anshulvj/libfreenect2/examples/protonect/src/libfreenect2.cpp:293: undefined reference to `libusb_free_device_list'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `libfreenect2::ChangeCurrentOpenGLContext::ChangeCurrentOpenGLContext(GLFWwindow*)':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:52: undefined reference to `glfwGetCurrentContext'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `libfreenect2::OpenGLDepthPacketProcessorImpl::startTiming()':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:450: undefined reference to `glfwGetTime'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `libfreenect2::OpenGLDepthPacketProcessor::process(libfreenect2::DepthPacket const&)':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:931: undefined reference to `glfwMakeContextCurrent'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `libfreenect2::OpenGLDepthPacketProcessorImpl::stopTiming()':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:455: undefined reference to `glfwGetTime'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `libfreenect2::OpenGLDepthPacketProcessor::process(libfreenect2::DepthPacket const&)':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:937: undefined reference to `glfwSwapBuffers'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `libfreenect2::OpenGLDepthPacketProcessor::OpenGLDepthPacketProcessor(void*, bool)':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:771: undefined reference to `glfwInit'
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:774: undefined reference to `glfwDefaultWindowHints'
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:775: undefined reference to `glfwWindowHint'
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:776: undefined reference to `glfwWindowHint'
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:780: undefined reference to `glfwWindowHint'
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:781: undefined reference to `glfwWindowHint'
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:783: undefined reference to `glfwCreateWindow'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `libfreenect2::ChangeCurrentOpenGLContext::ChangeCurrentOpenGLContext(GLFWwindow*)':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:53: undefined reference to `glfwMakeContextCurrent'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `libfreenect2::ChangeCurrentOpenGLContext::~ChangeCurrentOpenGLContext()':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:65: undefined reference to `glfwMakeContextCurrent'
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:65: undefined reference to `glfwMakeContextCurrent'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `~OpenGLDepthPacketProcessorImpl':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:407: undefined reference to `glfwDestroyWindow'
/usr/local/lib/libfreenect2.a(opengl_depth_packet_processor.cpp.o): In function `libfreenect2::OpenGLDepthPacketProcessorImpl::~OpenGLDepthPacketProcessorImpl()':
/home/anshulvj/libfreenect2/examples/protonect/src/opengl_depth_packet_processor.cpp:407: undefined reference to `glfwDestroyWindow'
/usr/local/lib/libfreenect2.a(transfer_pool.cpp.o): In function `libfreenect2::usb::TransferPool::deallocate()':
/home/anshulvj/libfreenect2/examples/protonect/src/transfer_pool.cpp:64: undefined reference to `libusb_free_transfer'
/usr/local/lib/libfreenect2.a(transfer_pool.cpp.o): In function `libfreenect2::usb::TransferPool::submit(unsigned long)':
/home/anshulvj/libfreenect2/examples/protonect/src/transfer_pool.cpp:94: undefined reference to `libusb_submit_transfer'
/home/anshulvj/libfreenect2/examples/protonect/src/transfer_pool.cpp:98: undefined reference to `libusb_error_name'
/usr/local/lib/libfreenect2.a(transfer_pool.cpp.o): In function `libfreenect2::usb::TransferPool::cancel()':
/home/anshulvj/libfreenect2/examples/protonect/src/transfer_pool.cpp:108: undefined reference to `libusb_cancel_transfer'
/home/anshulvj/libfreenect2/examples/protonect/src/transfer_pool.cpp:112: undefined reference to `libusb_error_name'
/usr/local/lib/libfreenect2.a(transfer_pool.cpp.o): In function `libfreenect2::usb::TransferPool::onTransferComplete(libfreenect2::usb::TransferPool::Transfer*)':
/home/anshulvj/libfreenect2/examples/protonect/src/transfer_pool.cpp:185: undefined reference to `libusb_submit_transfer'
/home/anshulvj/libfreenect2/examples/protonect/src/transfer_pool.cpp:189: undefined reference to `libusb_error_name'
/usr/local/lib/libfreenect2.a(transfer_pool.cpp.o): In function `libfreenect2::usb::BulkTransferPool::allocateTransfer()':
/home/anshulvj/libfreenect2/examples/protonect/src/transfer_pool.cpp:210: undefined reference to `libusb_alloc_transfer'
/usr/local/lib/libfreenect2.a(transfer_pool.cpp.o): In function `libfreenect2::usb::IsoTransferPool::allocateTransfer()':
/home/anshulvj/libfreenect2/examples/protonect/src/transfer_pool.cpp:247: undefined reference to `libusb_alloc_transfer'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `checkLibusbResult':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:194: undefined reference to `libusb_error_name'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `libfreenect2::protocol::libusb_ext::set_isochronous_delay(libusb_device_handle*, int)':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:80: undefined reference to `libusb_control_transfer'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `libfreenect2::protocol::libusb_ext::set_sel(libusb_device_handle*, int, unsigned char, unsigned char, unsigned char, unsigned char)':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:94: undefined reference to `libusb_control_transfer'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `libfreenect2::protocol::libusb_ext::set_feature_function_suspend(libusb_device_handle*, int, bool, bool)':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:128: undefined reference to `libusb_control_transfer'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `libfreenect2::protocol::libusb_ext::get_max_iso_packet_size(libusb_device*, int, int, int)':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:136: undefined reference to `libusb_get_config_descriptor_by_value'
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:162: undefined reference to `libusb_get_ss_endpoint_companion_descriptor'
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:174: undefined reference to `libusb_free_config_descriptor'
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:168: undefined reference to `libusb_free_ss_endpoint_companion_descriptor'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `libfreenect2::protocol::UsbControl::setConfiguration()':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:210: undefined reference to `libusb_get_configuration'
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:217: undefined reference to `libusb_set_configuration'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `libfreenect2::protocol::UsbControl::claimInterfaces()':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:230: undefined reference to `libusb_claim_interface'
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:235: undefined reference to `libusb_claim_interface'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `libfreenect2::protocol::UsbControl::releaseInterfaces()':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:247: undefined reference to `libusb_release_interface'
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:252: undefined reference to `libusb_release_interface'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `set_feature<libfreenect2::protocol::libusb_ext::DeviceFeatureSelector>':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:109: undefined reference to `libusb_control_transfer'
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:109: undefined reference to `libusb_control_transfer'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `libfreenect2::protocol::UsbControl::setIrInterfaceState(libfreenect2::protocol::UsbControl::State)':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:301: undefined reference to `libusb_set_interface_alt_setting'
/usr/local/lib/libfreenect2.a(usb_control.cpp.o): In function `libfreenect2::protocol::UsbControl::getIrMaxIsoPacketSize(int&)':
/home/anshulvj/libfreenect2/examples/protonect/src/usb_control.cpp:310: undefined reference to `libusb_get_device'
/usr/local/lib/libfreenect2.a(command_transaction.cpp.o): In function `libfreenect2::protocol::CommandTransaction::send(libfreenect2::protocol::CommandBase const&)':
/home/anshulvj/libfreenect2/examples/protonect/src/command_transaction.cpp:134: undefined reference to `libusb_bulk_transfer'
/home/anshulvj/libfreenect2/examples/protonect/src/command_transaction.cpp:138: undefined reference to `libusb_error_name'
/usr/local/lib/libfreenect2.a(command_transaction.cpp.o): In function `libfreenect2::protocol::CommandTransaction::receive(libfreenect2::protocol::CommandTransaction::Result&)':
/home/anshulvj/libfreenect2/examples/protonect/src/command_transaction.cpp:156: undefined reference to `libusb_bulk_transfer'
/home/anshulvj/libfreenect2/examples/protonect/src/command_transaction.cpp:160: undefined reference to `libusb_error_name'
/usr/local/lib/libfreenect2.a(event_loop.cpp.o): In function `libfreenect2::usb::EventLoop::execute()':
/home/anshulvj/libfreenect2/examples/protonect/src/event_loop.cpp:88: undefined reference to `libusb_handle_events_timeout_completed'
/usr/local/lib/libfreenect2.a(flextGL.c.o): In function `flextLoadOpenGLFunctions':
/home/anshulvj/libfreenect2/examples/protonect/src/flextGL.c:50: undefined reference to `glfwGetProcAddress'
/home/anshulvj/libfreenect2/examples/protonect/src/flextGL.c:51: undefined reference to `glfwGetProcAddress'
/home/anshulvj/libfreenect2/examples/protonect/src/flextGL.c:52: undefined reference to `glfwGetProcAddress'
/home/anshulvj/libfreenect2/examples/protonect/src/flextGL.c:53: undefined reference to `glfwGetProcAddress'
/home/anshulvj/libfreenect2/examples/protonect/src/flextGL.c:57: undefined reference to `glfwGetProcAddress'
/usr/local/lib/libfreenect2.a(flextGL.c.o):/home/anshulvj/libfreenect2/examples/protonect/src/flextGL.c:58: more undefined references to `glfwGetProcAddress' follow
/usr/local/lib/libfreenect2.a(flextGL.c.o): In function `flextInit':
/home/anshulvj/libfreenect2/examples/protonect/src/flextGL.c:20: undefined reference to `glfwGetWindowAttrib'
/home/anshulvj/libfreenect2/examples/protonect/src/flextGL.c:21: undefined reference to `glfwGetWindowAttrib'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/anshulvj/catkin_ws/devel/lib/kinect2_bridge/kinect2_bridge] Error 1
make[1]: *** [iai_kinect2/kinect2_bridge/CMakeFiles/kinect2_bridge.dir/all] Error 2
[100%] Built target kinect2_bridge_nodelet
make[2]: *** [iai_kinect2/kinect2_viewer/CMakeFiles/kinect2_viewer.dir/src/viewer.cpp.o] Error 1
make[1]: *** [iai_kinect2/kinect2_viewer/CMakeFiles/kinect2_viewer.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
anshulvj@anshulspc:~/catkin_ws$ 

**EDIT**:
------------------------------------
I deleted both libfreenect2 and iai_kinect2 workspaces and reinstalled both. libfreenect2 installed smoothly as usual. After re-catkin_make-ing iai_kinect2 workspace, the installation (rosdep command) yielded different errors (detailed below):

Scanning dependencies of target kinect2_registration
[ 14%] [ 28%] [ 42%] Building CXX object iai_kinect2/kinect2_registration/CMakeFiles/kinect2_registration.dir/src/kinect2_registration.cpp.o
Building CXX object iai_kinect2/kinect2_registration/CMakeFiles/kinect2_registration.dir/src/depth_registration_cpu.cpp.o
Building CXX object iai_kinect2/kinect2_registration/CMakeFiles/kinect2_registration.dir/src/depth_registration_opencl.cpp.o
Linking CXX shared library /home/anshulvj/catkin_ws/devel/lib/libkinect2_registration.so
[ 42%] Built target kinect2_registration
Scanning dependencies of target kinect2_viewer
Scanning dependencies of target kinect2_calibration
Scanning dependencies of target kinect2_bridge
Scanning dependencies of target kinect2_bridge_nodelet
[ 57%] Building CXX object iai_kinect2/kinect2_calibration/CMakeFiles/kinect2_calibration.dir/src/kinect2_calibration.cpp.o
[ 71%] Building CXX object iai_kinect2/kinect2_bridge/CMakeFiles/kinect2_bridge.dir/src/kinect2_bridge.cpp.o
[ 85%] Building CXX object iai_kinect2/kinect2_bridge/CMakeFiles/kinect2_bridge_nodelet.dir/src/kinect2_bridge.cpp.o
[100%] Building CXX object iai_kinect2/kinect2_viewer/CMakeFiles/kinect2_viewer.dir/src/viewer.cpp.o
/home/anshulvj/catkin_ws/src/iai_kinect2/kinect2_calibration/src/kinect2_calibration.cpp: In member function ‘void CameraCalibration::calibrateExtrinsics()’:
/home/anshulvj/catkin_ws/src/iai_kinect2/kinect2_calibration/src/kinect2_calibration.cpp:682:56: error: cannot convert ‘const cv::TermCriteria’ to ‘int’ for argument ‘13’ to ‘double cv::stereoCalibrate(cv::InputArrayOfArrays, cv::InputArrayOfArrays, cv::InputArrayOfArrays, cv::InputOutputArray, cv::InputOutputArray, cv::InputOutputArray, cv::InputOutputArray, cv::Size, cv::OutputArray, cv::OutputArray, cv::OutputArray, cv::OutputArray, int, cv::TermCriteria)’
                                 cv::CALIB_FIX_INTRINSIC);
                                                        ^
/home/anshulvj/catkin_ws/src/iai_kinect2/kinect2_calibration/src/kinect2_calibration.cpp: In member function ‘void DepthCalibration::getPlane(size_t, cv::Mat&, double&) const’:
/home/anshulvj/catkin_ws/src/iai_kinect2/kinect2_calibration/src/kinect2_calibration.cpp:969:138: error: ‘ITERATIVE’ is not a member of ‘cv’
     cv::solvePnPRansac(board, points[index], cameraMatrix, distortion, rvec, translation, false, 300, 0.05, board.size(), cv::noArray(), cv::ITERATIVE);
                                                                                                                                          ^
make[2]: *** [iai_kinect2/kinect2_calibration/CMakeFiles/kinect2_calibration.dir/src/kinect2_calibration.cpp.o] Error 1
make[1]: *** [iai_kinect2/kinect2_calibration/CMakeFiles/kinect2_calibration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library /home/anshulvj/catkin_ws/devel/lib/libkinect2_bridge_nodelet.so
Linking CXX executable /home/anshulvj/catkin_ws/devel/lib/kinect2_bridge/kinect2_bridge
[100%] Built target kinect2_bridge_nodelet
/usr/bin/ld: warning: libopencv_imgproc.so.3.0, needed by /home/anshulvj/catkin_ws/devel/lib/libkinect2_registration.so, may conflict with libopencv_imgproc.so.2.4
[100%] Built target kinect2_bridge
Linking CXX executable /home/anshulvj/catkin_ws/devel/lib/kinect2_viewer/kinect2_viewer
/usr/bin/ld: warning: libopencv_objdetect.so.2.4, needed by /usr/lib/x86_64-linux-gnu/libopencv_contrib.so.2.4.8, may conflict with libopencv_objdetect.so.3.0
[100%] Built target kinect2_viewer
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
anshulvj@anshulspc:~/catkin_ws$

**Comment by wiedemeyer** [comment]
Hi,
just install OpenCV and PCL from the official Ubuntu repositories. It will not work with OpenCV 3.0.0.
The rosdep error is normal. It is explained in the FAQ section of the [README](..).

**Comment by anshulvj** [comment]
Thanks Thiemo,

I only replaced Opencv3.0 with opencv 2.4.9 and it compiled successfully. Before that I also recompiled PCL from sources instead of using binaries but I don't know whether that made a difference.

Also, when I run kinect2_bridge I get the following error:

[ERROR] [1434379251.163641822]: [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...

I could not see anyone else getting this error in issues.

**Comment by anshulvj** [comment]
Ok. This was a classical noob error: I ran roscore in another terminal and then it worked. However, when I run kinect_bridge it gives out all the output with params etc, then waits saying "[kinect2_bridge] waiting for clients to connect". It's waiting for a while now. Any thoughts on how I should proceed?

**Comment by wiedemeyer** [comment]
It will wait for clients to connect. So as soon as you start listening to a topic, it will start processing data.

**Comment by anshulvj** [comment]
Meaning what should I do on the side while it's waiting for clients to connect, or starting receiver? Should I be opening another window and running another command or something?

**Comment by anshulvj** [comment]
Ok. I started roscore in one terminal, kinect2_bridge in another terminal, and kinect2_viewer in third terminal. This time it showed a window were it was apparently trying to display something. It was hard to see as it kept on refreshing (mostly all I could see was something magenta colored on the top half of the image) and the fps kept bouncing around

**Comment by wiedemeyer** [comment]
Please make sure to use the latest version of libfreenect2 and iai_kinect2, because there were changes that made the older versions incompatible to the newer ones.

**Comment by anshulvj** [comment]
I think I'm using the latest version since I re-cloned both of them in the last couple of days.

**Comment by wiedemeyer** [comment]
just make sure, because there were some updates in the last couple of days.

**Comment by anshulvj** [comment]
Thanks, I'll do that.

**Comment by wiedemeyer** [comment]
Did it work?

**Comment by anshulvj** [comment]
Sorry for the late reply, I was on vacation. Actually I did not try installing it later coz I figured out the equations for getting x,y,z locations from depth image, in the registration.cpp. So now I'm just using libfreenect2. Thanks for your suggestions though.

I had another question though. I haven't explored it yet, but maybe you might have an answer: is there any way to suspend/pause the kinect streaming process? I did some stress testing today and my embedded machine-being the low power machine it is- gets wedged if it runs protonect for too long. I wanted to know if there was anything simple I could do to pause the process and resume it quickly, to shed some load?

**Comment by wiedemeyer** [comment]
Right now, if no topics are subscribed, the kinect2_bridge shuts down the device and the processing. So simply unsubscribe if you don't need data. Also you could limit the fps to a lower value.
I saw your issue https://github.com/OpenKinect/libfreenect2/issues/307 there. If there is a pause in libfreenect2, I could replace the shutdown by a pause, so that it can start processing more quickly.

**Comment by anshulvj** [comment]
I have created a pause() function as suggested by @floe, in https://github.com/OpenKinect/libfreenect2/issues/307, and it seems to be working. I.e. I pause for a few seconds, after a fixed number of frames have been accessed, then reset the frame counter and continue again (by calling SetStreamEnabledCommand..).
