### ISSUE TITLE
Unable to compile anymore

### ISSUE THREAD

**Issue by soulslicer** [code-iai/iai_kinect2#377]
```
/usr/local/include/opencv2/flann/saving.h:113:63: error: exception handling disabled, use -fexceptions to enable
         throw FLANNException("Invalid index file, cannot read");
```

I am getting the following error when compiling

**Comment by soulslicer** [comment]
This happens in the kinect registration package. However, when I added the following line to the kinect_registration CMakeLists.txt, it works

`add_definitions( -fexceptions )`

**Comment by EXing** [comment]
@soulslicer it helps!!!!!

**Comment by wiedemeyer** [comment]
Never seen this error. Could it be that you are not using the version that comes with Ubuntu?

**Comment by EXing** [comment]
I don't know! I'm in ubuntu 16.04. before it, the project has already been built. then, it happens come with some other errors.

**Comment by VasLem** [comment]
I confirm there was an installation error and that @soulslicer solution fixed it. I was forced to reinstall the whole iai_kinect2 after the latest ROS Kinetic update, as it rendered my previous installation buggy. The folowing error appeared that forced me to reinstall:
```
[ERROR] [1489029105.365911194]: Failed to load nodelet [/kinect2_bridge] of type [kinect2_bridge/kinect2_bridge_nodelet] even after refreshing the cache: Could not find library corresponding to plugin kinect2_bridge/kinect2_bridge_nodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
```

**Comment by soulslicer** [comment]
This is an issue with the new OpenCV update 3.2.0

**Comment by zipeilu** [comment]
Same issue occurred to me after the the latest ROS update. Every node of iai_kinect2 didn't work and failed to locate the libopencv_improc3.so. I tried to recompile iai_kinect2 then this issue came out. After all, @soulslicer 's solution works really well! Thanks a lot!

**Comment by TheTesla** [comment]
please look here: #397 
This fixed the problem for me

**Comment by alansrobotlab** [comment]
I can confirm.  Saw the same problem with nvidia cuda + opencl install on 16.04 kinetic.

Inserted "add_definitions( -fexceptions )" and allowed catkin_make to complete:
```
if(OpenCL_FOUND)
  message(STATUS "OpenCL based depth registration enabled")
  set(EXPORTED_DEPENDENCIES OpenCL)
  add_definitions( -fexceptions )
```

Error seen during catkin_make without -fexceptions:
```
In file included from /opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/flann/flann_base.hpp:41:0,
                 from /opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/flann.hpp:48,
                 from /opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/opencv.hpp:62,
                 from /home/grey/inmoov_ros/src/iai_kinect2/kinect2_registration/include/kinect2_registration/kinect2_registration.h:24,
                 from /home/grey/inmoov_ros/src/iai_kinect2/kinect2_registration/src/kinect2_registration.cpp:18:
/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/flann/saving.h: In function ‘cvflann::IndexHeader cvflann::load_header(FILE*)’:
/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/flann/saving.h:113:63: error: exception handling disabled, use -fexceptions to enable
         throw FLANNException("Invalid index file, cannot read");
```

**Comment by yoneken** [comment]
This issue is still exist on 16.04 kinetic.. #397 is also useful for me.

**Comment by aadityacr7** [comment]
Its working. Thank you so much @soulslicer . 

Works on Ubuntu 16.04, ROS-Kinetic, Kinect V2

**Comment by aaronsnoswell** [comment]
I saw the same issue on my machine - Ubuntu 16.04, ROS Kinetic. Making the changes suggested by @alansrobotlab fixed it for me. I suggest pulling #397.

**Comment by christian-rauch** [comment]
Disabling the exception checking is enforced at
https://github.com/code-iai/iai_kinect2/blob/4d41e24c4728d917af928b8a4a6cf236849ba8d4/kinect2_registration/CMakeLists.txt#L66

Removing (or commenting) this line also solves the problem.
